# src/utils/ui_trans.py

UI_TRANSLATIONS = {
    "english": {
        "verified": "VERIFIED:",
        "global": "[GLOBAL]",
        "who_affected": "👥 Who is Affected",
        "why_matters": "⚡ Why It Matters",
        "key_points": "Key Points",
        "why_it_matters": "Why it Matters",
        "impact_analysis": "Impact Analysis",
        "ai_analysis": "AI Analysis",
        "just_now": "Just Now",
        "brief_title": "⭐ 60-Second Brief",
        "see_more": "See More",
        "see_more_briefs": "See More Briefs",
        "top_headlines": "Top Headlines",
        "breaking_news": "Breaking News",
        "live_updates": "LIVE UPDATES",
        "system_init": "System Initializing...",
        "gathering_intel": "Gathering intelligence from global nodes. Please wait for the next cycle.",
        "global_system_init": "⚙️ Global System Initializing",
        "status": "Status:",
        "syncing": "Syncing...",
        "ai_engine_sync": "The AI Intelligence engine is performing its first major sync with world news sources. This node will be active within 5-10 minutes.",
        "node_backup_active": "📡 Node Intelligence Backup Active",
        "regional_gathering": "Regional news for this specific node is currently gathering. Displaying **Global Intelligence** as a temporary backup.",
        "try_sync_node": "Try Sync Node",
        "main_dashboard": "Main Dashboard",
        "trending_feed": "Trending Feed",
        "viral": "VIRAL",
        "no_trending": "No specific trending data currently available.",
        "todays_newspapers": "Today's Newspapers",
        "regional_publications": "Regional Publications",
        "universal_news": "UNIVERSAL NEWS INTELLIGENCE",
        "update_cycle": "⚡ 15-Minute Update Cycle",
        "last_updated": "Last Updated:",
        "ai_generated": "AI-generated summaries. Verify with original sources.",
        "all_rights": "All rights reserved.",
        "markets": "MARKETS",
        "live_report": "LIVE REPORT",
        "confirmed": "Confirmed",
        "breaking_feed": "BREAKING FEED",
        "global_intel_node": "Global Intelligence Node",
        "regional_intel_feed": "Regional intelligence feed for",
        "curated_intel": "Curated intelligence:",
        "categories": "Categories",
        "global_nodes": "Global Nodes",
        "saved_items": "Saved Items",
        "mock_test": "Mock Test",
        "history": "History",
        "analyst_reports": "Analyst Reports",
        "intelligence_report": "Intelligence Report",
        "verified_source": "VERIFIED SOURCE",
        "neutral": "Neutral",
        "exec_summary": "📌 Executive Summary",
        "analyzing_demo": "Analyzing demographic impact...",
        "evaluating_strat": "Evaluating strategic significance...",
        "intel_tags": "INTEL TAGS",
        "save_for_later": "🔖 Save For Later",
        "visit_source": "🌐 VISIT ORIGINAL SOURCE",
        "for_students": "FOR STUDENTS",
        "personal_ai_news": "PERSONAL AI NEWS",
        "crystal_ball": "CRYSTAL BALL",
        "home": "Home",
        "category": "Category",
        "nodes": "Global Nodes",
        "saved": "Saved",
        "universe": "Universe",
        "test": "Mock Test",
        "history_nav": "History",
        "news_nav": "Newspaper",
        "search_lang": "Search language...",
        "indian_langs": "Indian Languages",
        "global_langs": "Global Languages",
        "select_language": "Select Your Language",
        "universe_hero_title": "Global Intelligence Explorer",
        "universe_hero_desc": "Access real-time news analysis from the world's major nodes.",
        "scan_node": "SCAN NODE",
        "video_reports": "Video Reports",
        "strategic_intel": "Strategic Intelligence",
        "daily_intel_briefing": "DAILY INTEL BRIEFING",
        "details": "Details",
        "close": "CLOSE X",
        "sports": "Sports",
        "politics": "Politics",
        "business": "Business",
        "technology": "Technology",
        "ai": "AI",
        "world": "World",
        "india": "India",
        "science": "Science",
        "entertainment": "Entertainment",
        "china": "China",
        "japan": "Japan",
        "uk": "UK",
        "usa": "USA",
        "russia": "Russia",
        "germany": "Germany",
        "france": "France",
        "australia": "Australia",
        "singapore": "Singapore",
        "uae": "UAE",
        "sign_in": "Sign in",
        "sign_up": "Sign up",
        "create_account": "Create account",
        "no_account": "Don't have an account?",
        "already_have_account": "Already have an account?",
        "create_now": "Create now",
        "share_intel": "Share Intelligence",
        "track_intel": "Track Intelligence",
        "force_update": "Force AI Update",
        "search_placeholder": "Search global intelligence...",
        "recent_intel": "Recent AI Intelligence",
        "verified_global": "Verified Global Feed",
        "trending_global": "Trending in Global",
        "back_to_top": "Back to Top",
        "status_ready": "System Active",
        "intel_node": "Node",
        "intelligence": "Intelligence",
        "asset_sp500": "S&P 500",
        "asset_nasdaq": "NASDAQ",
        "asset_nifty": "NIFTY 50",
        "asset_btc": "BTC",
        "asset_gold": "GOLD",
        "asset_crude": "CRUDE OIL",
        "weather_cloudy": "Partly Cloudy",
        "weather_sunny": "Sunny",
        "weather_rainy": "Rainy",
        'listen_audi': 'Listen',
        'stop_audi': 'Stop',
        'playing': 'Playing...',
        "student_portal_title": "Student Intelligence Hub",
        "student_portal_subtitle": "Real-time tracking of exams, policies, scholarships, and opportunities parsed directly from the news without delay.",
        "active_opportunities": "Active Opportunities",
        "trending_topic": "Trending Topic",
        "live_scholarships": "Live Scholarships",
        "scholarships_internships": "Scholarships & Internships",
        "exams_results": "Exams & Results",
        "admissions_courses": "Admissions & Courses",
        "career_jobs": "Career & Jobs",
        "apply_now": "Apply Now →",
        "search_country": "Search Country",
        "all_updates": "All Updates",
        "region_country": "Region / Country",
        "choose_preferred_language": "Choose your preferred language for the Universal News Intelligence feed.",
        "skip_continue_english": "Skip — Continue in English",
        "student_section": {
            "title": "Student Intelligence",
            "subtitle": "Scholarships, exams, admissions, and career updates",
            "all_updates": "All Updates",
            "scholarships": "Scholarships & Internships",
            "exams": "Exams & Results",
            "admissions": "Admissions & Courses",
            "career": "Career & Jobs",
            "policy": "Education & Policy"
        }
    },
    "telugu": {
        "verified": "ధృవీకరించబడింది:",
        "global": "[గ్లోబల్]",
        "who_affected": "👥 ఎవరు ప్రభావితమవుతారు",
        "why_matters": "⚡ ఎందుకు ముఖ్యమైనది",
        "key_points": "ముఖ్య అంశాలు",
        "why_it_matters": "ఎందుకు ఇది ముఖ్యం",
        "impact_analysis": "ప్రభావ విశ్లేషణ",
        "ai_analysis": "AI విశ్లేషణ",
        "just_now": "ఇప్పుడే",
        "brief_title": "⭐ 60-సెకన్ల సంక్షిప్త సమాచారం",
        "see_more": "మరింత చూడండి",
        "see_more_briefs": "మరిన్ని బ్రీఫ్‌లు చూడండి",
        "top_headlines": "ముఖ్య వార్తలు",
        "breaking_news": "బ్రేకింగ్ న్యూస్",
        "live_updates": "లైవ్ అప్‌డేట్స్",
        "system_init": "సిస్టమ్ ప్రారంభమవుతోంది...",
        "gathering_intel": "గ్లోబల్ నోడ్స్ నుండి సమాచారం సేకరిస్తోంది...",
        "global_system_init": "⚙️ గ్లోబల్ సిస్టమ్ సింక్ అవుతోంది",
        "status": "స్థితి:",
        "syncing": "సింక్ అవుతోంది...",
        "ai_engine_sync": "AI ఇంజిన్ మొదట ప్రపంచ వార్తా వనరులతో సమకాలీకరిస్తోంది. 5-10 నిమిషాల్లో ఈ నోడ్ యాక్టివ్ అవుతుంది.",
        "node_backup_active": "📡 నోడ్ బ్యాకప్ యాక్టివ్",
        "regional_gathering": "ప్రాంతీయ వార్తలు సేకరిస్తున్నాము. తాత్కాలికంగా గ్లోబల్ ఇంజెలిజెన్స్ చూపుతున్నాము.",
        "try_sync_node": "మళ్లీ సింక్ చేయండి",
        "main_dashboard": "ప్రధాన డాష్‌బోర్డ్",
        "trending_feed": "ట్రెండింగ్ న్యూస్",
        "viral": "వైరల్",
        "no_trending": "ప్రస్తుతం ట్రెండింగ్ సమాచారం అందుబాటులో లేదు.",
        "todays_newspapers": "నేటి వార్తాపత్రికలు",
        "regional_publications": "ప్రాంతీయ ప్రచురణలు",
        "universal_news": "యూనివర్సల్ న్యూస్ ఇంటెలిజెన్స్",
        "update_cycle": "⚡ 15-నిమిషాల అప్‌డేట్",
        "last_updated": "చివరి అప్‌డేట్:",
        "ai_generated": "AI-సృష్టించిన సారాంశాలు. ఒరిజినల్ సోర్స్‌లతో ధృవీకరించుకోండి.",
        "all_rights": "సర్వ హక్కులూ ప్రత్యేకించబడినవి.",
        "markets": "మార్కెట్లు",
        "live_report": "లైవ్ రిపోర్্ট",
        "confirmed": "నిర్ధారించబడింది",
        "breaking_feed": "బ్రేకింగ్ ఫీడ్",
        "global_intel_node": "గ్లోబల్ నోడ్",
        "regional_intel_feed": "ప్రాంతీయ ఫీడ్: ",
        "curated_intel": "క్యూరేటెడ్ వార్తలు:",
        "categories": "వర్గాలు",
        "global_nodes": "గ్లోబల్ నోడ్స్",
        "saved_items": "సేవ్ చేయబడినవి",
        "mock_test": "మాక్ టెస్ట్",
        "history": "చరిత్ర",
        "analyst_reports": "అనలిస్ట్ రిపోర్ట్స్",
        "intelligence_report": "ఇంటెలిజెన్స్ రిపోర్ట్",
        "verified_source": "నమ్మకమైన వనరు",
        "neutral": "తటస్థం",
        "exec_summary": "📌 సారాంశం",
        "analyzing_demo": "ప్రభావం విశ్లేషించబడుతోంది...",
        "evaluating_strat": "ప్రాముఖ్యత మదింపు చేయబడుతోంది...",
        "intel_tags": "ట్యాగ్స్",
        "save_for_later": "🔖 సేవ్ చేయండి",
        "visit_source": "🌐 అసలు మూలాన్ని సందర్శించండి",
        "for_students": "విద్యార్థుల కోసం",
        "personal_ai_news": "వ్యక్తిగత AI వార్తలు",
        "crystal_ball": "క్రిస్టల్ బాల్",
        "home": "హోమ్",
        "category": "వర్గం",
        "nodes": "గ్లోబల్ నోడ్స్",
        "saved": "సేవ్ చేసినవి",
        "universe": "విశ్వం",
        "test": "మాక్ టెస్ట్",
        "history_nav": "చరిత్ర",
        "news_nav": "వార్తాపత్రిక",
        "search_lang": "భాషను వెతకండి...",
        "indian_langs": "భారతీయ భాషలు",
        "global_langs": "ప్రపంచ భాషలు",
        "select_language": "మీ భాషను ఎంచుకోండి",
        "universe_hero_title": "గ్లోబల్ ఇంటెలిజెన్స్ ఎక్స్‌ప్లోరర్",
        "universe_hero_desc": "ప్రపంచంలోని ప్రధాన నోడ్ల నుండి నిజ-సమయ వార్తల విశ్లేషణను పొందండి.",
        "scan_node": "నోడ్ స్కాన్ చేయండి",
        "video_reports": "వీడియో నివేదికలు",
        "strategic_intel": "ವ್ಯೂಹಾತ್ಮಕ సమాచారం",
        "daily_intel_briefing": "రోజువారీ ఇంటెల్ బ్రీఫింగ్",
        "details": "వివరాలు",
        "close": "ముగించు X",
        "sports": "క్రీడలు",
        "politics": "రాజకీయాలు",
        "business": "వ్యాపారం",
        "technology": "సాంకేతికత",
        "ai": "AI",
        "world": "ప్రపంచం",
        "india": "భారతదేశం",
        "science": "సైన్స్",
        "entertainment": "వినోదం",
        "china": "చైనా",
        "japan": "జపాన్",
        "uk": "UK",
        "usa": "అమెరికా",
        "russia": "రష్యా",
        "germany": "జర్మనీ",
        "france": "ఫ్రాన్స్",
        "australia": "ఆస్ట్రేలియా",
        "singapore": "సింగపూర్",
        "uae": "UAE",
        "sign_in": "సైన్ ఇన్",
        "sign_up": "సైన్ అప్",
        "create_account": "ఖాతాను సృష్టించండి",
        "no_account": "ఖాతా లేదా?",
        "already_have_account": "ఇప్పటికే ఖాతా ఉందా?",
        "create_now": "ఇప్పుడే సృష్టించండి",
        "share_intel": "సమాచారాన్ని పంచుకోండి",
        "track_intel": "వార్తలను ఫాలో అవ్వండి",
        "force_update": "AI అప్‌డేట్",
        "quick_chat": "త్వరిత చాట్",
        "search_placeholder": "ప్రపంచ వార్తలను వెతకండి...",
        "recent_intel": "ఇటీవలి AI వార్తలు",
        "verified_global": "ధృవీకరించబడిన గ్లోబల్ ఫీడ్",
        "trending_global": "ప్రపంచ ట్రెండ్స్",
        "back_to_top": "పైకి వెళ్ళండి",
        "status_ready": "సిస్టమ్ సిద్ధంగా ఉంది",
        "intel_node": "నోడ్",
        "intelligence": "సమాచారం",
        "asset_sp500": "ఎస్&పీ 500",
        "asset_nasdaq": "నాస్డాక్",
        "asset_nifty": "నిఫ్టీ 50",
        "asset_btc": "బిట్ కాయిన్",
        "asset_gold": "బంగారం",
        "asset_crude": "ముడి చమురు",
        "weather_cloudy": "పాక్షికంగా మేఘావృతమై ఉంది",
        "weather_sunny": "ఎండగా ఉంది",
        "weather_rainy": "వర్షం పడుతోంది",
        "listen_audi": "వినండి",
        "stop_audi": "ఆపు",
        "playing": "ప్లే అవుతోంది...",
        "choose_preferred_language": "మీ ఫీడ్ కోసం ప్రాధాన్యత గల భాషను ఎంచుకోండి.",
        "skip_continue_english": "దాటవేయి — ఇంగ్లీష్‌లో కొనసాగించండి",
        "student_portal_title": "స్టూడెంట్ ఇంటెలిజెన్స్ హబ్",
        "student_portal_subtitle": "పరీక్షలు, విధానాలు, స్కాలర్‌షిప్‌లు మరియు అవకాశాల రియల్ టైమ్ ట్రాకింగ్.",
        "active_opportunities": "చురుకైన అవకాశాలు",
        "trending_topic": "ట్రెండింగ్ టాపిక్",
        "live_scholarships": "లైవ్ స్కాలర్‌షిప్‌లు",
        "scholarships_internships": "స్కాలర్‌షిప్‌లు & ఇంటర్న్‌షిప్‌లు",
        "exams_results": "పరీక్షలు & ఫలితాలు",
        "admissions_courses": "అడ్మిషన్లు & కోర్సులు",
        "career_jobs": "కెరీర్ & ఉద్యోగాలు",
        "apply_now": "ఇప్పుడే దరఖాస్తు చేసుకోండి →",
        "search_country": "దేశాన్ని వెతకండి",
        "all_updates": "అన్ని అప్‌డేట్‌లు",
        "region_country": "ప్రాంతం / దేశం",
        "student_section": {
            "title": "స్టూడెంట్ ఇంటెలిజెన్స్",
            "subtitle": "స్కాలర్‌షిప్‌లు, పరీక్షలు, ప్రవేశాలు మరియు కెరీర్ అప్‌డేట్‌లు",
            "all_updates": "అన్ని అప్‌డేట్‌లు",
            "scholarships": "స్కాలర్‌షిప్‌లు & ఇంటర్న్‌షిప్‌లు",
            "exams": "పరీక్షలు & ఫలితాలు",
            "admissions": "అడ్మిషన్లు & కోర్సులు",
            "career": "కెరీర్ & ఉద్యోగాలు",
            "policy": "విద్య & విధానం"
        }
    },
    "hindi": {
        "verified": "सत्यापित:",
        "global": "[वैश्विक]",
        "who_affected": "👥 कौन प्रभावित है",
        "why_matters": "⚡ यह क्यों मायने रखता है",
        "key_points": "मुख्य बिंदु",
        "why_it_matters": "यह क्यों मायने रखता है",
        "impact_analysis": "प्रभाव विश्लेषण",
        "ai_analysis": "AI विश्लेषण",
        "just_now": "अभी-अभी",
        "brief_title": "⭐ 60-सेकंड की जानकारी",
        "see_more": "और देखें",
        "see_more_briefs": "और जानकारी देखें",
        "top_headlines": "मुख्य समाचार",
        "breaking_news": "ब्रेकिंग न्यूज़",
        "live_updates": "लाइव अपडेट्स",
        "system_init": "सिस्टम प्रारंभ हो रहा है...",
        "gathering_intel": "जानकारी एकत्र की जा रही है...",
        "global_system_init": "⚙️ ग्लोबल सिस्टम सिंक हो रहा है",
        "status": "स्थिति:",
        "syncing": "सिंक हो रहा है...",
        "ai_engine_sync": "AI इंजन दुनिया भर के समाचारों के साथ सिंक कर रहा है। 5-10 मिनट प्रतीक्षा करें।",
        "node_backup_active": "📡 बैकअप सक्रिय है",
        "regional_gathering": "क्षेत्रीय समाचार एकत्र किए जा रहे हैं। अस्थायी रूप से वैश्विक समाचार दिखाए जा रहे हैं।",
        "try_sync_node": "फिर से सिंक करें",
        "main_dashboard": "मुख्य डैशबोर्ड",
        "trending_feed": "ट्रेंडिंग न्यूज़",
        "viral": "वायरल",
        "no_trending": "कोई ट्रेंडिंग डेटा उपलब्ध नहीं है।",
        "todays_newspapers": "आज के समाचार पत्र",
        "regional_publications": "क्षेत्रीय प्रकाशन",
        "universal_news": "यूनिवर्सल न्यूज़ इंटेलिजेंस",
        "update_cycle": "⚡ 15 मिनट का अपडेट साइकल",
        "last_updated": "अंतिम अपडेट:",
        "ai_generated": "AI जनरेटेड सारांश। मूल स्रोतों से पुष्टि करें।",
        "all_rights": "सर्वाधिकार सुरक्षित।",
        "markets": "बाज़ार",
        "live_report": "लाइव रिपोर्ट",
        "confirmed": "पुष्टि हो चुकी है",
        "breaking_feed": "ब्रेकिंग फ़ीड",
        "global_intel_node": "ग्लोबल नोड",
        "regional_intel_feed": "क्षेत्रीय फ़ीड: ",
        "curated_intel": "विशेष समाचार:",
        "categories": "श्रेणियां",
        "global_nodes": "ग्लोबल नोड्स",
        "saved_items": "सेव किए गए आइटम",
        "mock_test": "मॉक टेस्ट",
        "history": "इतिहास",
        "analyst_reports": "एनालिस्ट रिपोर्ट्स",
        "intelligence_report": "इंटेलिजेंस रिपोर्ट",
        "verified_source": "सत्यापित स्रोत",
        "neutral": "तटस्थ",
        "exec_summary": "📌 सारांश",
        "analyzing_demo": "प्रभाव का विश्लेषण किया जा रहा है...",
        "evaluating_strat": "रणनीतिक महत्व का मूल्यांकन...",
        "intel_tags": "टैग्स",
        "save_for_later": "🔖 सेव करें",
        "visit_source": "🌐 मूल स्रोत पर जाएं",
        "for_students": "छात्रों के लिए",
        "personal_ai_news": "व्यक्तिगत AI समाचार",
        "crystal_ball": "क्रिस्टल बॉल",
        "home": "होम",
        "category": "श्रेणी",
        "search_lang": "भाषा खोजें...",
        "indian_langs": "भारतीय भाषाएं",
        "global_langs": "वैश्विक भाषाएं",
        "select_language": "अपनी भाषा चुनें",
        "universe_hero_title": "वैश्विक खुफिया एक्सप्लोरर",
        "universe_hero_desc": "दुनिया के प्रमुख नोड्स से वास्तविक समय के समाचार विश्लेषण तक पहुंचें।",
        "scan_node": "नोड स्कैन करें",
        "video_reports": "वीडियो रिपोर्ट",
        "strategic_intel": "रणनीतिक खुफिया",
        "daily_intel_briefing": "दैनिक खुफिया ब्रीफिंग",
        "details": "विवरण",
        "close": "बंद करें X",
        "sports": "खेल",
        "politics": "राजनीति",
        "business": "व्यापार",
        "technology": "तकनीक",
        "ai": "AI",
        "world": "विश्व",
        "india": "भारत",
        "science": "विज्ञान",
        "entertainment": "मनोरंजन",
        "china": "चीन",
        "japan": "जापान",
        "uk": "UK",
        "usa": "अमेरिका",
        "russia": "रूस",
        "germany": "जर्मनी",
        "france": "फ्रांस",
        "australia": "ऑस्ट्रेलिया",
        "singapore": "सिंगापुर",
        "uae": "संयुक्त अरब अमीरात",
        "sign_in": "साइन इन",
        "sign_up": "साइन अप",
        "create_account": "खाता बनाएं",
        "no_account": "खाता नहीं है?",
        "already_have_account": "पहले से ही खाता है?",
        "create_now": "अभी बनाएं",
        "share_intel": "खुफिया जानकारी साझा करें",
        "track_intel": "ट्रैक इंटेलिजेंस",
        "force_update": "एआई अपडेट",
        "quick_chat": "त्वरित चैट",
        "search_placeholder": "दुनिया भर की खुफिया जानकारी खोजें...",
        "recent_intel": "हालिया एआई इंटेलिजेंस",
        "verified_global": "सत्यापित वैश्विक फ़ीड",
        "trending_global": "वैश्विक रुझान",
        "back_to_top": "वापस ऊपर",
        "status_ready": "सिस्टम सक्रिय है",
        "intel_node": "नोड",
        "intelligence": "इंटेलिजेंस",
        "listen_audi": "सुनें",
        "stop_audi": "बंद करें",
        "playing": "चल रहा है...",
        "choose_preferred_language": "अपनी न्यूज़ फीड के लिए अपनी पसंदीदा भाषा चुनें।",
        "skip_continue_english": "छोड़ें — अंग्रेजी में जारी रखें",
        "student_portal_title": "छात्र इंटेलिजेंस हब",
        "student_portal_subtitle": "परीक्षाओं, नीतियों, छात्रवृत्तियों और समाचारों से सीधे पार्स किए गए अवसरों की वास्तविक समय की ट्रैकिंग।",
        "active_opportunities": "सक्रिय अवसर",
        "trending_topic": "ट्रेंडिंग टॉपिक",
        "live_scholarships": "लाइव छात्रवृत्तियां",
        "scholarships_internships": "छात्रवृत्ति और इंटर्नशिप",
        "exams_results": "परीक्षा और परिणाम",
        "admissions_courses": "प्रवेश और पाठ्यक्रम",
        "career_jobs": "कैरियर और नौकरियां",
        "apply_now": "अभी आवेदन करें →",
        "search_country": "देश खोजें",
        "all_updates": "सभी अपडेट",
        "region_country": "क्षेत्र / देश",
        "student_section": {
            "title": "छात्र इंटेलिजेंस",
            "subtitle": "छात्रवृत्ति, परीक्षा, प्रवेश और करियर अपडेट",
            "all_updates": "सभी अपडेट",
            "scholarships": "छात्रवृत्ति और इंटर्नशिप",
            "exams": "परीक्षा और परिणाम",
            "admissions": "प्रवेश और पाठ्यक्रम",
            "career": "करियर और नौकरियां",
            "policy": "शिक्षा और नीति"
        }
    },
    "spanish": {
        "verified": "VERIFICADO:",
        "global": "[GLOBAL]",
        "who_affected": "👥 Quiénes se ven afectados",
        "why_matters": "⚡ Por qué es importante",
        "ai_analysis": "Análisis de IA",
        "just_now": "Ahora",
        "brief_title": "⭐ Resumen de 60 Segundos",
        "see_more": "Ver Más",
        "see_more_briefs": "Ver Más Resúmenes",
        "top_headlines": "Titulares Principales",
        "breaking_news": "Noticias de Última Hora",
        "live_updates": "ACTUALIZACIONES EN VIVO",
        "system_init": "Inicializando...",
        "gathering_intel": "Recopilando inteligencia... ",
        "global_system_init": "⚙️ Sincronización Global de Sistemas",
        "status": "Estado:",
        "syncing": "Sincronizando...",
        "ai_engine_sync": "El motor de inteligencia está realizando su primera sincronización importante.",
        "node_backup_active": "📡 Inteligencia Global de Respaldo",
        "regional_gathering": "Buscando noticias regionales. Mostrando noticias globales como respaldo...",
        "try_sync_node": "Sincronizar",
        "main_dashboard": "Panel Principal",
        "trending_feed": "Tendencias",
        "viral": "VIRAL",
        "no_trending": "Sin datos de tendencias en este momento.",
        "todays_newspapers": "Periódicos de Hoy",
        "regional_publications": "Publicaciones Regionales",
        "universal_news": "INTELIGENCIA DE NOTICIAS UNIVERSAL",
        "update_cycle": "⚡ Ciclo de actualización de 15 min",
        "last_updated": "Última actualización:",
        "ai_generated": "Resúmenes generados por IA. Verifique con fuentes originales.",
        "all_rights": "Todos los derechos reservados.",
        "markets": "MERCADOS",
        "live_report": "REPORTE EN VIVO",
        "confirmed": "Confirmado",
        "breaking_feed": "FEED DE ÚLTIMA HORA",
        "global_intel_node": "Nodo de Inteligencia Global",
        "regional_intel_feed": "Inteligencia regional para:",
        "curated_intel": "Inteligencia curada:",
        "categories": "Categorías",
        "global_nodes": "Nodos Globales",
        "saved_items": "Guardado",
        "mock_test": "Prueba",
        "history": "Historial",
        "analyst_reports": "Informes Analíticos",
        "intelligence_report": "Reporte de Inteligencia",
        "verified_source": "FUENTE VERIFICADA",
        "neutral": "Neutral",
        "exec_summary": "📌 Resumen Ejecutivo",
        "analyzing_demo": "Analizando impacto...",
        "evaluating_strat": "Evaluando el significado...",
        "intel_tags": "ETIQUETAS INTEL",
        "save_for_later": "🔖 Guardar para más tarde",
        "visit_source": "🌐 VISITAR FUENTE ORIGINAL",
        "intel_node": "Nodo",
        "intelligence": "Inteligencia",
        "for_students": "Para Estudiantes",
        "personal_ai_news": "Noticias de IA Personal",
        "crystal_ball": "Bola de Cristal",
        "choose_preferred_language": "Elija su idioma preferido para las noticias.",
        "student_section": {
            "title": "Inteligencia Estudiantil",
            "subtitle": "Becas, exámenes, admisiones y actualizaciones de carrera",
            "all_updates": "Todas las actualizaciones",
            "scholarships": "Becas y pasantías",
            "exams": "Exámenes y resultados",
            "admissions": "Admisiones y cursos",
            "career": "Carrera y empleos",
            "policy": "Educación y política"
        }
    },
    "punjabi": {
        "verified": "ਤਸਦੀਕ ਕੀਤੀ:",
        "global": "[ਗਲੋਬਲ]",
        "who_affected": "👥 ਕੌਣ ਪ੍ਰਭਾਵਿਤ ਹੈ",
        "why_matters": "⚡ ਇਹ ਕਿਉਂ ਮਹੱਤਵਪੂਰਨ ਹੈ",
        "key_points": "ਮੁੱਖ ਨੁਕਤੇ",
        "why_it_matters": "ਇਹ ਕਿਉਂ ਮਹੱਤਵਪੂਰਨ ਹੈ",
        "impact_analysis": "ਪ੍ਰਭਾਵ ਵਿਸ਼ਲੇਸ਼ਣ",
        "ai_analysis": "AI ਵਿਸ਼ਲੇਸ਼ਣ",
        "just_now": "ਹੁਣੇ",
        "brief_title": "⭐ 60-ਸਕਿੰਟ ਦਾ ਸਾਰ",
        "see_more": "ਹੋਰ ਦੇਖੋ",
        "see_more_briefs": "ਹੋਰ ਸਾਰ ਦੇਖੋ",
        "top_headlines": "ਮੁੱਖ ਖ਼ਬਰਾਂ",
        "breaking_news": "ਬ੍ਰੇਕਿੰਗ ਨਿਊਜ਼",
        "live_updates": "ਲਾਈਵ ਅੱਪਡੇਟ",
        "system_init": "ਸਿਸਟਮ ਸ਼ੁਰੂ ਹੋ ਰਿਹਾ ਹੈ...",
        "gathering_intel": "ਜਾਣਕਾਰੀ ਇਕੱਠੀ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
        "status": "ਸਥਿਤੀ:",
        "syncing": "ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...",
        "main_dashboard": "ਮੁੱਖ ਡੈਸ਼ਬੋਰਡ",
        "universal_news": "ਯੂਨੀਵਰਸਲ ਨਿਊਜ਼",
        "update_cycle": "⚡ 15-ਮਿੰਟ ਦਾ ਅੱਪਡੇਟ",
        "for_students": "ਵਿਦਿਆਰਥੀਆਂ ਲਈ",
        "personal_ai_news": "ਨਿੱਜੀ AI ਖ਼ਬਰਾਂ",
        "student_portal_title": "ਵਿਦਿਆਰਥੀ ਜਾਣਕਾਰੀ ਕੇਂਦਰ",
        "scholarships_internships": "ਸਕਾਲਰਸ਼ਿਪ ਅਤੇ ਇੰਟਰਨਸ਼ਿਪ",
        "exams_results": "ਪ੍ਰੀਖਿਆਵਾਂ ਅਤੇ ਨਤੀਜੇ",
        "apply_now": "ਹੁਣੇ ਅਪਲਾਈ ਕਰੋ →",
        "student_section": {
            "title": "ਵਿਦਿਆਰਥੀ ਜਾਣਕਾਰੀ",
            "subtitle": "ਸਕਾਲਰਸ਼ਿਪ, ਪ੍ਰੀਖਿਆਵਾਂ, ਦਾਖਲੇ ਅਤੇ ਕਰੀਅਰ ਅੱਪਡੇਟ",
            "all_updates": "ਸਾਰੇ ਅੱਪਡੇਟ",
            "scholarships": "ਸਕਾਲਰਸ਼ਿਪ ਅਤੇ ਇੰਟਰਨਸ਼ਿਪ",
            "exams": "ਪ੍ਰੀਖਿਆਵਾਂ ਅਤੇ ਨਤੀਜੇ",
            "admissions": "दाखले ਅਤੇ ਕੋਰਸ",
            "career": "ਕਰੀਅਰ ਅਤੇ ਨੌਕਰੀਆਂ",
            "policy": "ਸਿੱਖਿਆ ਅਤੇ ਨੀਤੀ"
        }
    },
    "marathi": {
        "verified": "सत्यापित:",
        "global": "[जागतिक]",
        "who_affected": "👥 कोणावर परिणाम होतो",
        "why_matters": "⚡ हे का महत्त्वाचे आहे",
        "key_points": "ठळक मुद्दे",
        "why_it_matters": "हे महत्त्वाचे का आहे",
        "impact_analysis": "प्रभाव विश्लेषण",
        "ai_analysis": "AI विश्लेषण",
        "just_now": "आत्ता",
        "brief_title": "⭐ ६०-सेकंद सारांश",
        "see_more": "आणखी पहा",
        "top_headlines": "प्रमुख बातम्या",
        "breaking_news": "ब्रेकिंग न्यूज",
        "live_updates": "लाईव्ह अपडेट्स",
        "system_init": "सिस्टम सुरू होत आहे...",
        "status": "स्थिती:",
        "syncing": "सिंक होत आहे...",
        "universal_news": "युनिव्हर्सल न्यूज",
        "for_students": "विद्यार्थ्यांसाठी",
        "save_for_later": "🔖 नंतरसाठी जतन करा",
        "student_portal_title": "विद्यार्थी माहिती केंद्र",
        "scholarships_internships": "शिष्यवृत्ती आणि इंटर्नशिप",
        "exams_results": "परीक्षा आणि निकाल",
        "apply_now": "आता अर्ज करा →",
        "student_section": {
            "title": "विद्यार्थी इंटेलिजेंस",
            "subtitle": "शिष्यवृत्ती, परीक्षा, प्रवेश आणि करिअर अपडेट्स",
            "all_updates": "सर्व अपडेट्स",
            "scholarships": "शिष्यवृत्ती आणि इंटर्नशिप",
            "exams": "परीक्षा आणि निकाल",
            "admissions": "प्रवेश आणि अभ्यासक्रम",
            "career": "करिअर आणि नोकऱ्या",
            "policy": "शिक्षण आणि धोरण"
        }
    },
    "bengali": {
        "verified": "যাচাইকৃত:",
        "global": "[বৈশ্বিক]",
        "who_affected": "👥 কারা প্রভাবিত",
        "why_matters": "⚡ কেন এটি গুরুত্বপূর্ণ",
        "key_points": "মূল পয়েন্ট",
        "why_it_matters": "কেন এটি গুরুত্বপূর্ণ",
        "impact_analysis": "প্রভাব বিশ্লেষণ",
        "ai_analysis": "AI বিশ্লেষণ",
        "just_now": "এইমাত্র",
        "brief_title": "⭐ ৬০-সেকেন্ডের সংক্ষিপ্তসার",
        "see_more": "আরও দেখুন",
        "top_headlines": "শীর্ষ সংবাদ",
        "breaking_news": "ব্রেকিং নিউজ",
        "live_updates": "লাইভ আপডেট",
        "system_init": "সিস্টেম শুরু হচ্ছে...",
        "status": "অবস্থা:",
        "syncing": "সিঙ্ক হচ্ছে...",
        "universal_news": "ইউনিভার্সাল নিউজ",
        "for_students": "শিক্ষার্থীদের জন্য",
        "student_portal_title": "ছাত্র তথ্য কেন্দ্র",
        "scholarships_internships": "বৃত্তি এবং ইন্টার্নশিপ",
        "exams_results": "পরীক্ষা এবং ফলাফল",
        "apply_now": "এখনই আবেদন করুন →",
        "student_section": {
            "title": "ছাত্র ইন্টেলিজেন্স",
            "subtitle": "বৃত্তি, পরীক্ষা, ভর্তি এবং ক্যারিয়ার আপডেট",
            "all_updates": "সমস্ত আপডেট",
            "scholarships": "বৃত্তি এবং ইন্টার্নশিপ",
            "exams": "পরীক্ষা এবং ফলাফল",
            "admissions": "ভর্তি এবং কোর্স",
            "career": "ক্যারিয়ার এবং চাকরি",
            "policy": "শিক্ষা এবং নীতি"
        }
    },
    "tamil": {
        "verified": "சரிபார்க்கப்பட்டது:",
        "global": "[உலகளாவிய]",
        "who_affected": "👥 யார் பாதிக்கப்படுகிறார்கள்",
        "why_matters": "⚡ இது ஏன் முக்கியமானது",
        "key_points": "முக்கிய குறிப்புகள்",
        "why_it_matters": "ஏன் இது முக்கியமானது",
        "impact_analysis": "தாக்க பகுப்பாய்வு",
        "ai_analysis": "AI பகுப்பாய்வு",
        "just_now": "இப்போது",
        "brief_title": "⭐ 60-வினாடி சுருக்கம்",
        "see_more": "மேலும் காண்க",
        "top_headlines": "தலைப்புச் செய்திகள்",
        "breaking_news": "முக்கிய செய்திகள்",
        "live_updates": "நேரಡಿ அறிவிப்புகள்",
        "system_init": "கணினி தொடங்குகிறது...",
        "status": "நிலை:",
        "syncing": "ஒத்திசைக்கப்படுகிறது...",
        "universal_news": "யுனிவர்சல் நியூஸ்",
        "for_students": "மாணவர்களுக்காக",
        "student_portal_title": "மாணவர் தகவல் மையம்",
        "scholarships_internships": "உதவித்தொகை மற்றும் இன்டர்ன்ஷிப்",
        "exams_results": "தேர்வுகள் மற்றும் முடிவுகள்",
        "apply_now": "இப்பொழுதே விண்ணப்பிக்கவும் →",
        "student_section": {
            "title": "மாணவர் இன்டெலிஜென்ஸ்",
            "subtitle": "உதவித்தொகை, தேர்வுகள், சேர்க்கை மற்றும் தொழில் குறித்த அறிவிப்புகள்",
            "all_updates": "அனைத்து அறிவிப்புகளும்",
            "scholarships": "உதவித்தொகை & இன்டர்ன்ஷிப்",
            "exams": "தேர்வுகள் & முடிவுகள்",
            "admissions": "சேர்க்கை & படிப்புகள்",
            "career": "தொழில் & வேலைகள்",
            "policy": "கல்வி & கொள்கை"
        }
    },
    "kannada": {
        "verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ:",
        "global": "[ಜಾಗತಿಕ]",
        "who_affected": "👥 ಯಾರು ಬಾಧಿತರಾಗಿದ್ದಾರೆ",
        "why_matters": "⚡ ಇದು ಏಕೆ ಮುಖ್ಯ",
        "key_points": "ಮುಖ್ಯಾಂಶಗಳು",
        "why_it_matters": "ಇದು ಏಕೆ ಮುಖ್ಯ",
        "impact_analysis": "ಪರಿಣಾಮ ವಿಶ್ಲೇಷಣೆ",
        "ai_analysis": "AI ವಿಶ್ಲೇಷಣೆ",
        "just_now": "ಈಗಷ್ಟೇ",
        "brief_title": "⭐ 60-ಸೆಕೆಂಡ್ ಸಾರಾಂಶ",
        "see_more": "ಇನ್ನಷ್ಟು ನೋಡಿ",
        "top_headlines": "ಮುಖ್ಯಾಂಶಗಳು",
        "breaking_news": "ಬ್ರೇಕಿಂಗ್ ನ್ಯೂಸ್",
        "live_updates": "ಲೈವ್ ನವೀಕರಣಗಳು",
        "system_init": "ಸಿಸ್ಟಮ್ ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ...",
        "status": "ಸ್ಥಿತಿ:",
        "syncing": "ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...",
        "universal_news": "ಯೂನಿವರ್ಸಲ್ ನ್ಯೂಸ್",
        "for_students": "ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ",
        "student_portal_title": "ವಿದ್ಯಾರ್ಥಿ ಮಾಹಿತಿ ಕೇಂದ್ರ",
        "scholarships_internships": "ಶಿಷ್ಯವೇತನ ಮತ್ತು ಇಂಟರ್ನ್ಶಿಪ್",
        "exams_results": "ಪರೀಕ್ಷೆಗಳು ಮತ್ತು ಫಲಿತಾಂಶಗಳು",
        "apply_now": "ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ →",
        "student_section": {
            "title": "ವಿದ್ಯಾರ್ಥಿ ಇಂಟೆಲಿಜೆನ್ಸ್",
            "subtitle": "ಶಿಷ್ಯವೇತನಗಳು, ಪರೀಕ್ಷೆಗಳು, ಪ್ರವೇಶಗಳು మరియు వృత్తిజీవನದ అప్‌డేట్‌లు",
            "all_updates": "ಎಲ್ಲಾ అప్‌డేట్‌లు",
            "scholarships": "ಶಿಷ್ಯವೇತನಗಳು & ಇಂಟర్ನ್‌ಶಿಪ್‌లు",
            "exams": "ಪರೀಕ್ಷೆಗಳು & ಫಲಿತಾಂಶಗಳು",
            "admissions": "ಪ್ರವೇಶಗಳು & ಕೋರ್ಸ್‌ಗಳು",
            "career": "ವೃತ್ತಿజీವನ & ಉದ್ಯೋಗಗಳು",
            "policy": "ಶಿಕ್ಷಣ & ನೀತಿ"
        }
    },
    "malayalam": {
        "verified": "സ്ഥിരീകരിച്ചു:",
        "global": "[ആഗോള]",
        "who_affected": "👥 ആരെ ബാധിക്കുന്നു",
        "why_matters": "⚡ എന്തുകൊണ്ട് ഇത് പ്രധാനമാണ്",
        "key_points": "പ്രധാന പോയിന്റുകൾ",
        "why_it_matters": "എന്തുകൊണ്ട് ഇത് പ്രധാനമാണ്",
        "impact_analysis": "പ്രത്യാഘാത വിശകലനം",
        "ai_analysis": "AI വിശകലനം",
        "just_now": "ഇപ്പോൾ",
        "brief_title": "⭐ 60-സെക്കൻഡ് സംഗ്രഹം",
        "see_more": "കൂടുതൽ കാണുക",
        "top_headlines": "പ്രധാന വാർത്തകൾ",
        "breaking_news": "ബ്രേക്കിംഗ് വാർത്തകൾ",
        "live_updates": "തത്സമയ അപ്‌ഡേറ്റുകൾ",
        "system_init": "സിസ്റ്റം ആരംഭിക്കുന്നു...",
        "status": "നില:",
        "syncing": "സിങ്ക് ചെയ്യുന്നു...",
        "universal_news": "യൂണിവേഴ്സൽ ന്യൂസ്",
        "for_students": "വിദ്യാർത്ഥികൾക്കായി",
        "student_portal_title": "വിദ്യാർത്ഥി വിവര കേന്ദ്രം",
        "scholarships_internships": "സ്കോളർഷിപ്പും ഇന്റേൺഷിപ്പും",
        "exams_results": "പരീക്ഷകളും ഫലങ്ങളും",
        "apply_now": "ഇപ്പോൾ അപേക്ഷിക്കുക →",
        "student_section": {
            "title": "സ്റ്റുഡന്റ് ഇന്റലിജൻസ്",
            "subtitle": "സ്കോളർഷിപ്പുകൾ, പരീക്ഷകൾ, പ്രവേശനം, കരിയർ അപ്ഡേറ്റുകൾ",
            "all_updates": "എല്ലാ അപ്ഡേറ്റുകളും",
            "scholarships": "സ്കോളർഷിപ്പുകൾ & ഇന്റേൺഷിപ്പുകൾ",
            "exams": "പരീക്ഷകൾ & ഫലങ്ങൾ",
            "admissions": "പ്രവേശനം & കോഴ്സുകൾ",
            "career": "കരിയർ & ജോലികൾ",
            "policy": "വിദ്യാഭ്യാസം & നയം"
        }
    },
    "arabic": {
        "visit_source": "🌐 المصدر الأصلي",
        "intel_node": "نود",
        "intelligence": "استخبارات",
        "for_students": "للطلاب",
        "personal_ai_news": "أخبار الذكاء الاصطناعي الشخصية",
        "crystal_ball": "الكرة الكريستالية",
        "choose_preferred_language": "اختر لغتك المفضلة لموجز الأخبار.",
        "skip_continue_english": "تخطي - تابع بالإنجليزية",
        "student_section": {
            "title": "ذكاء الطلاب",
            "subtitle": "المنح الدراسية والامتحانات والقبول وتحديثات الحياة المهنية",
            "all_updates": "كل التحديثات",
            "scholarships": "المنح الدراسية والتدريب",
            "exams": "الامتحانات والنتائج",
            "admissions": "القبول والدورات",
            "career": "الوظائف والمهن",
            "policy": "التعليم والسياسة"
        }
    },
    "japanese": {
        "verified": "確認済み:",
        "global": "[グローバル]",
        "who_affected": "👥 影響を受けるのは誰か",
        "why_matters": "⚡ なぜ重要か",
        "ai_analysis": "AI分析",
        "just_now": "たった今",
        "brief_title": "⭐ 60秒の要約",
        "see_more": "もっと見る",
        "see_more_briefs": "さらに表示",
        "top_headlines": "主要な見出し",
        "breaking_news": "ニュース速報",
        "live_updates": "ライブアップデート",
        "system_init": "システム初期化中...",
        "gathering_intel": "情報を収集しています...",
        "global_system_init": "⚙️ グローバルシステム同期中",
        "status": "ステータス:",
        "syncing": "同期中...",
        "ai_engine_sync": "AIエンジンがニュースソースと同期しています。5〜10分お待ちください。",
        "node_backup_active": "📡 バックアップを使用中",
        "regional_gathering": "地域ニュースを収集中のため、一時的にグローバルニュースを表示しています。",
        "try_sync_node": "再同期する",
        "main_dashboard": "メインダッシュボード",
        "trending_feed": "トレンドニュース",
        "viral": "話題",
        "no_trending": "トレンドデータはありません。",
        "todays_newspapers": "今日の新聞",
        "regional_publications": "地域の出版物",
        "universal_news": "ユニバーサル・ニュース",
        "update_cycle": "⚡ 15分ごとの更新サイクル",
        "last_updated": "最終更新:",
        "ai_generated": "AI生成の要約です。元のソースで確認してください。",
        "all_rights": "無断転載を禁じます。",
        "markets": "市場",
        "live_report": "ライブレポート",
        "confirmed": "確認済み",
        "breaking_feed": "ニュースフィード",
        "global_intel_node": "グローバル情報ノード",
        "regional_intel_feed": "地域の情報フィード:",
        "curated_intel": "厳選情報:",
        "categories": "カテゴリー",
        "global_nodes": "グローバルノード",
        "saved_items": "保存済み",
        "mock_test": "模擬テスト",
        "history": "履歴",
        "analyst_reports": "アナリストレポート",
        "intelligence_report": "情報のレポート",
        "verified_source": "確認済みの情報源",
        "neutral": "中立",
        "exec_summary": "📌 エグゼクティブサマリー",
        "analyzing_demo": "影響を分析中...",
        "evaluating_strat": "重要度を評価中...",
        "intel_tags": "インテルタグ",
        "save_for_later": "🔖 後で保存",
        "visit_source": "🌐 元のソースを訪問",
        "intel_node": "ノード",
        "intelligence": "インテリジェンス",
        "for_students": "学生向け",
        "personal_ai_news": "パーソナルAIニュース",
        "crystal_ball": "クリスタルボール",
        "choose_preferred_language": "ニュースフィードの希望の言語を選択してください。",
        "skip_continue_english": "スキップ — 英語で続行",
        "student_section": {
            "title": "学生インテリジェンス",
            "subtitle": "奨学金、試験、入学、キャリアの最新情報",
            "all_updates": "すべての更新",
            "scholarships": "奨学金とインターンシップ",
            "exams": "試験と結果",
            "admissions": "入学とコース",
            "career": "キャリアと仕事",
            "policy": "教育と政策"
        }
    },
    "french": {
        "verified": "VÉRIFIÉ:",
        "global": "[GLOBAL]",
        "who_affected": "👥 Qui est concerné ?",
        "why_matters": "⚡ Pourquoi c'est important",
        "ai_analysis": "Analyse IA",
        "just_now": "À l'instant",
        "brief_title": "⭐ En Bref (60s)",
        "see_more": "Voir plus",
        "see_more_briefs": "Voir tous les résumés",
        "top_headlines": "À la Une",
        "breaking_news": "Dernière Heure",
        "live_updates": "EN DIRECT",
        "system_init": "Initialisation...",
        "gathering_intel": "Collecte en cours...",
        "global_system_init": "⚙️ Initialisation du système global",
        "status": "Statut :",
        "syncing": "Synchronisation...",
        "ai_engine_sync": "L'IA se synchronise with les sources. Cela prendra 5-10 minutes.",
        "node_backup_active": "📡 Sauvegarde des données active",
        "regional_gathering": "Bascule temporaire vers l'information globale.",
        "try_sync_node": "Réessayer",
        "main_dashboard": "Tableau de Bord Principal",
        "trending_feed": "Tendances",
        "viral": "VIRAL",
        "no_trending": "Aucune tendance pour le moment.",
        "todays_newspapers": "Les journaux d'aujourd'hui",
        "regional_publications": "Publications régionales",
        "universal_news": "UNIVERSAL NEWS",
        "update_cycle": "⚡ Cycle de mise à jour: 15min",
        "last_updated": "Dernière MÀJ:",
        "ai_generated": "Résumé IA. Vérifiez l'original.",
        "all_rights": "Tous droits réservés.",
        "markets": "MARCHÉS",
        "live_report": "Rapport Direct",
        "confirmed": "Confirmé",
        "breaking_feed": "FIL INFO",
        "global_intel_node": "Information Globale",
        "regional_intel_feed": "Information régionale pour:",
        "curated_intel": "Information validée:",
        "categories": "Categoríes",
        "global_nodes": "Nœuds",
        "saved_items": "Sauvegardés",
        "mock_test": "Test",
        "history": "Historique",
        "analyst_reports": "Rapports Experts",
        "intelligence_report": "Rapport Synthétique",
        "verified_source": "SOURCE VÉRIFIÉE",
        "neutral": "Neutre",
        "exec_summary": "📌 Résumé",
        "analyzing_demo": "Analyse d'impact...",
        "evaluating_strat": "Évaluation...",
        "intel_tags": "TAGS",
        "save_for_later": "🔖 Enregistrer",
        "visit_source": "🌐 SOURCE ORIGINALE",
        "intel_node": "Nœud",
        "intelligence": "Intelligence",
        "for_students": "Pour les étudiants",
        "personal_ai_news": "Actualités IA Personnelles",
        "crystal_ball": "Boule de Cristal",
        "choose_preferred_language": "Choisissez votre langue préférée pour le flux d'informations.",
        "skip_continue_english": "Passer — Continuer en Anglais",
        "student_section": {
            "title": "Intelligence Étudiante",
            "subtitle": "Bourses, examens, admissions et mises à jour de carrière",
            "all_updates": "Toutes les mises à jour",
            "scholarships": "Bourses & Stages",
            "exams": "Examens & Résultats",
            "admissions": "Admissions & Cours",
            "career": "Carrière & Emplois",
            "policy": "Éducation & Politique"
        }
    }
}

def get_ui_labels(lang: str) -> dict:
    """Helper to fetch localized UI labels for backend-driven article objects."""
    l = lang.lower().strip()
    
    # Map short codes if needed
    mapping = {
        "hi": "hindi", "te": "telugu", "ta": "tamil", "ka": "kannada", 
        "ml": "malayalam", "mr": "marathi", "bn": "bengali", "gu": "gujarati",
        "pa": "punjabi"
    }
    l = mapping.get(l, l)

    if l == 'telugu':
        return {
            "key_points": "ముఖ్య అంశాలు",
            "why_it_matters": "ఎందుకు ఇది ముఖ్యం",
            "who_affected": "ఎవరు ప్రభావితమవుతారు"
        }
    elif l == 'hindi':
        return {
            "key_points": "मुख्य बिंदु",
            "why_it_matters": "यह क्यों मायने रखता है",
            "who_affected": "कौन प्रभावित है"
        }
    elif l == 'tamil':
        return {
            "key_points": "முக்கிய குறிப்புகள்",
            "why_it_matters": "ஏன் இது முக்கியமானது",
            "who_affected": "யார் பாதிக்கப்படுகிறார்கள்"
        }
    elif l == 'kannada':
        return {
            "key_points": "ಮುಖ್ಯಾಂಶಗಳು",
            "why_it_matters": "ಇದು ಏಕೆ ಮುಖ್ಯ",
            "who_affected": "ಯಾರು ಬಾಧಿತರು"
        }
    elif l == 'malayalam':
        return {
            "key_points": "പ്രധാന പോയിന്റുകൾ",
            "why_it_matters": "എന്തുകൊണ്ട് ഇത് പ്രധാനമാണ്",
            "who_affected": "ആരെ ബാധിക്കുന്നു"
        }
    elif l == 'bengali':
        return {
            "key_points": "মূল পয়েন্ট",
            "why_it_matters": "কেন এটি গুরুত্বপূর্ণ",
            "who_affected": "কারা প্রভাবিত"
        }
    elif l == 'gujarati':
        return {
            "key_points": "મુખ્ય મુદ્દાઓ",
            "why_it_matters": "શા માટે તે મહત્વનું છે",
            "who_affected": "કોણ પ્રભાવિત છે"
        }
    elif l == 'marathi':
        return {
            "key_points": "ठळक मुद्दे",
            "why_it_matters": "हे महत्त्वाचे का आहे",
            "who_affected": "कोणावर परिणाम झाला"
        }
    elif l == 'punjabi':
        return {
            "key_points": "ਮੁੱਖ ਨੁਕਤੇ",
            "why_it_matters": "ਇਹ ਕਿਉਂ ਮਹੱਤਵਪੂਰਨ ਹੈ",
            "who_affected": "ਕੌਣ ਪ੍ਰਭਾਵਿਤ ਹੈ"
        }
    # Add more as needed
    return {
        "key_points": "Key Points",
        "why_it_matters": "Why It Matters",
        "who_affected": "Who is Affected"
    }

def get_ui_translations(lang: str) -> dict:
    if not lang:
        return UI_TRANSLATIONS["english"]
    lang = lang.lower().strip()
    
    # Map short codes to full names
    mapping = {
        "en": "english", "hi": "hindi", "te": "telugu", "ta": "tamil",
        "ka": "kannada", "ml": "malayalam", "mr": "marathi", "bn": "bengali",
        "gu": "gujarati", "ar": "arabic", "fr": "french", "es": "spanish",
        "pa": "punjabi"
    }
    lang = mapping.get(lang, lang)
    
    return UI_TRANSLATIONS.get(lang, UI_TRANSLATIONS.get("english"))
